### ISSUE TITLE
Sequelize Migration Example Error

### ISSUE THREAD

**Issue by vikeen** [feathersjs/feathers-demos#20] opened 2016-09-17 16:30 UTC
I pulled down the last feathersjs code and when I try to run a migration:create command I get this error.

```bash
$ ./node_modules/sequelize-cli/bin/sequelize migration:create                                                                 1 ↵

Sequelize [Node: 5.6.0, CLI: 2.4.0, ORM: 3.24.3]

Successfully created migrations folder at "/Users/johnrake/dev/personal/feathers-demos/examples/migrations/sequelize/migrations".
Error reading "migrations/config/config.js". Error: Cannot read property 'replace' of null
```

As you can see from the logging my versions are `Sequelize [Node: 5.6.0, CLI: 2.4.0, ORM: 3.24.3]`. The error, however, is not obvious to me at all. Is there an easy way to actually debug this error or get the real stack trace?

When using the `--version` flag on the sequelize cli I get this:

```bash
$ ./node_modules/sequelize-cli/bin/sequelize --version

Sequelize [Node: 5.6.0, CLI: 2.4.0, ORM: 3.24.3]

CLI version 3.9.1
```

That makes the issue even more confusing because the module package.json clearly says `^2.4.0`

```bash
$ cat node_modules/sequelize-cli/package.json | grep -i version
  "_nodeVersion": "4.3.1",
  "_npmVersion": "2.14.12",
  "version": "2.4.0"
```

**Comment by daffl** [comment] 2016-09-19 23:19
@DesignByOnyx Any thoughts? It might have to be updated?

**Comment by DesignByOnyx** [comment] 2016-09-20 02:30
Hey, @vikeen - I wrote the sequelize migration docs and actively use the techniques described on my current project. That error is familiar and is generally an error caused by an issue in my application code (meaning, the error isn't in the config file - obviously). Unfortunately the CLI tool is swallowing the source of the error.

Whenever I see this error, I simply run my app and 99.9% of the time get a meaningful stack trace - usually an error in my models or services or something like that.  If you can run your app without issue, then check the files which are related to your migration code. Unfortunately this is the only information or advice I have for you at the moment. 

Since you have experienced this issue too, we should file a feature request with the sequelize-cli team. I'd like to wait to see if you can hunt down the solution to your problem so that we can have a clearer picture of a solution path.

**Comment by daffl** [comment] 2016-09-28 05:15
Thanks for following up! I'm going to close this since it looks more like something directly related to Sequelize.

**Closed by daffl** 2016-09-28 05:15 UTC
